Don't let addrev count the author as a reviewer
openssl/tools pull request #105
Opened 2022-02-21 11:37 UTC by mattcaswell

As per the latest policy change the author is no longer counted as a
reviewer, so we ensure addrev disallows this.

2022-02-21 12:38 UTC, levitte commented
Comparing with the rev tag is a bit over the top. I'm on the move, so will review more closely later

2022-02-21 16:27 UTC, mattcaswell commented
> Comparing with the rev tag is a bit over the top. I'm on the move, so will review more closely later

The idea was to ensure that the author email from the commit was in some kind of canonical form. You could possibly assume that the author email is already in the canonical format...?

2022-02-21 16:35 UTC, mattcaswell commented
For example consider the situation where the author email address is a different email address to the author rev tag address - but they are actually the same person? I can see some actual commits where this is the case.

2022-02-21 19:01 UTC, levitte requested changes
A nit

2022-02-21 19:01 UTC, levitte commented on review-tools/gitaddrev
> +if !$trivial && grep { $_ eq $author } (@nocla_reviewers);
This line should be indented 4 spaces (it should always have been, it was sloppy coding not to).  Also, the parenthesis is unnecessary, and frankly a bit confusing...

2022-02-21 19:01 UTC, levitte commented
> Comparing with the rev tag is a bit over the top. I'm on the move, so will review more closely later

It was too quick a look.  Upon looking again, I see the logic

2022-02-22 00:29 UTC, paulidale commented
> For example consider the situation where the author email address is a different email address to the author rev tag address - but they are actually the same person? I can see some actual commits where this is the case.

This only matters if it is a committer who is the author.  That reduces the risk significantly.

2022-02-22 11:03 UTC, mattcaswell commented
> This only matters if it is a committer who is the author. That reduces the risk significantly.

Ironically, the "actual commits" where this occurred that I'm talking about were yours @paulidale :-)

2022-02-23 13:23 UTC, mattcaswell commented
Fixup pushed addressing feedback. Please take another look.

2022-02-24 19:58 UTC, t-j-h approved these changes

2022-02-24 22:52 UTC, paulidale approved these changes

2022-02-25 07:04 UTC, levitte approved these changes

2022-02-25 15:21 UTC, mattcaswell commented
Does the 24h timer apply in this repo? I'm not sure. Also not sure about the 2 reviewer count (although I got that anyway).

2022-02-28 06:56 UTC, paulidale commented
@mattcaswell, they are good questions.  Moot now that the time and review count are there.

2022-02-28 11:29 UTC, mattcaswell commented
Pushed.

2022-02-28 11:29 UTC, closed without merging