gmerge and pick-to-branch: further tweak output
openssl/tools pull request #111
Opened 2022-03-15 12:19 UTC by DDvO

Add a log output, a message, and some empty lines to make the overall output more readable.

2022-03-15 13:10 UTC, t8m requested changes

2022-03-15 17:54 UTC, DDvO commented on review-tools/ghmerge
> -echo
I removed this log output because it was redundant - see lines 266 to268.

2022-03-16 08:56 UTC, t8m commented on review-tools/ghmerge
> -echo
Ah, you're right.

2022-03-16 08:57 UTC, t8m approved these changes

2022-03-17 13:46 UTC, t8m commented
Needs second review

2022-03-17 14:24 UTC, mspncp approved these changes
LGTM

2022-03-19 09:12 UTC, DDvO commented
This appears ready to merge -
can someone with sufficient privilege please do.

2022-03-21 02:25 UTC, paulidale approved these changes

2022-03-21 02:35 UTC, paulidale commented
Merged.  Any idea about the empty `remote:` lines that have appeared?

E.g. from this merge:
>remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
>remote: 
>remote: 
>To github.openssl.org:otc/tools.git

2022-03-21 09:12 UTC, t8m commented
> Any idea about the empty `remote:` lines that have appeared?

I suspect they are coming from the GHE hooks.

2022-09-24 15:32 UTC, DDvO commented
I cannot find this commit via my upstream repo reference `git@github.com:openssl/tools.git`.
Was it pushed to some other place or which is the current repo address that I should use?

2022-09-26 07:50 UTC, t8m commented
Hmm it seems it was somehow lost.

2022-09-26 07:50 UTC, t8m commented
Not sure how that happened.

2022-09-26 07:57 UTC, t8m commented
OK, pushed again.

2022-09-26 07:57 UTC, closed without merging

2022-09-26 09:27 UTC, DDvO commented
Thanks @t8m - now I can see it via my upstream remote `git@github.com:openssl/tools.git`.