Move OpenSSL-Query from omc-tools
openssl/tools pull request #170
Opened 2023-11-06 08:30 UTC by levitte

Fixes #134

2023-11-06 16:05 UTC, mspncp approved these changes
LGTM: both tree hashes of OpenSSL-Query are identical (3c2c7c4de4f20ea525ee40fe409446d66997dd16)

**omc-tools**
```
msp@debian:~/openssl/omc-tools$ git show --oneline --no-patch 
463e1f6 (HEAD -> master, origin/master, origin/HEAD) README.md: minor enhancements
msp@debian:~/openssl/omc-tools$ git rev-parse HEAD:OpenSSL-Query
3c2c7c4de4f20ea525ee40fe409446d66997dd16
```
**tools**
```
msp@debian:~/openssl/tools$ git show --oneline --no-patch 
4127ad4 (HEAD -> gh-170, github/gh-170) Move OpenSSL-Query from omc-tools
msp@debian:~/openssl/tools$ git rev-parse HEAD:OpenSSL-Query
3c2c7c4de4f20ea525ee40fe409446d66997dd16
```

2023-11-06 16:22 UTC, mspncp requested changes
One nit:

2023-11-06 16:22 UTC, mspncp commented on OpenSSL-Query/Makefile.PL
> +   bugtracker => 'https://github.com/openssl/omc-tools/issues',
```suggestion
   repository => 'https://github.com/openssl/tools.git',
   bugtracker => 'https://github.com/openssl/tools/issues',
```

2023-11-06 16:23 UTC, mspncp commented on OpenSSL-Query/Makefile.PL
> +   bugtracker => 'https://github.com/openssl/omc-tools/issues',
found by

    git diff 0d8b3195d26d3382e4580633b49e0626225dfdad~:OpenSSL-Query HEAD:OpenSSL-Query

2023-11-07 05:51 UTC, mspncp approved these changes

2023-11-07 19:04 UTC, levitte commented
@openssl/otc, another review needed please

2023-11-08 00:21 UTC, paulidale approved these changes

2023-11-08 06:05 UTC, levitte commented
Merged

e31cc768643d8ea5b8974f1f871bceaeeca3718c Move OpenSSL-Query from omc-tools

2023-11-08 06:37 UTC, closed without merging