remove FTP mention
openssl/tools pull request #187
Opened 2024-04-03 13:04 UTC by quarckster

We shut down the FTP server and should not mention it in our release announcements.

2024-04-03 13:06 UTC, t8m requested changes
Let's mention also the https://github.com/openssl/openssl/releases URL as the first step towards potential migration to GH for the source tarballs distribution.

2024-04-03 13:14 UTC, arapov requested changes

2024-04-03 13:14 UTC, arapov commented on release-tools/release-aux/openssl-announce-release-public.tmpl
> +   OpenSSL $release is available for download on these URLs:
```suggestion
   The OpenSSL $release is available for download at these URLs:
```

2024-04-03 13:14 UTC, arapov commented on release-tools/release-aux/openssl-announce-pre-release.tmpl
> +   The $label release is available for download on these URLs:
```suggestion
   The $label release is available for download at these URLs:
```

2024-04-03 13:38 UTC, arapov approved these changes

2024-04-04 23:12 UTC, paulidale approved these changes

2024-04-05 07:08 UTC, t8m commented
Squashed and merged. Thank you.

2024-04-05 07:08 UTC, closed without merging